/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.schemaregistry.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages="org.ga4gh.schemaregistry.controller")
public class App {
    public String getGreeting() {
        return "This is App!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);

    }
}
